version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8081:80"
    networks:
      - frontend-network
    environment:
      - REACT_APP_API_URL=http://20.67.233.69:3457

networks:
  frontend-network:
    driver: bridge